
const products = [
    {
      id: 1,
      name: 'No Weapon Formed Against Me Will Prosper',
      date: 2022,
      collection: "Black Dog",
      price: 3000,
      image: ['/images/endscene.jpg'],
      media: 'Graphite and marker on paper, digital collage',
      dimensions: "3x3ft",
      description: 'A beautiful abstract painting for your art collection.',
    },
    {
      id: 2,
      name: 'When the soul breaks through the confines of its mortal frame',
      date: 2021,
      collection: '',
      price: 2000,
      image: ['/images/nihilist.jpg'],
      media: 'Graphite, acrylic, marker on paper, digital collage',
      dimensions: "24x18in",
      description: 'This artwork depicts contrasting versions of myself, with the older self situated in a taxi\'s passenger seat while the younger self occupies the backseat. The scene captures the tension between these two personas, as the older self, symbolizing the mortal frame tied to the physical realm, faces the younger self brandishing a silencer. The aging appearance of the older self serves as a poignant reminder of the inherent limitations in our existence, while the younger self embodies the intellectual aspect of the soul, fervently seeking to transcend the boundaries of the physical world and empirical knowledge, even at the cost of confronting its own limitations.',
    },
    // Add more product entries as needed
    {
        id: 3,
        name: 'SAP(FORTHESOUL)',
        date: 2022,
        collection: '',
        price: 10000,
        image: ['/images/SAP.JPG'],
        media: '3D model sculpture, PIR motion sensor, DFPlayer, SD card, jumper wires, arduino uno',
        dimensions: "9x10x4in",
        description: 'Distorted sculpture of an African plaque that speaks using PIR motion sensor and arduino programming within the model. The speech generated is about existential and absurdist ideas that comes from a compilation of written words by Jean-Paul Sartre, Albert Camus and myself altered by text to speech software.',
      },

      {
        id: 4,
        name: 'The Paradox of the Absurdist',
        date: 2022,
        collection: '',
        price: 1000,
        image: ['/images/absurdist.jpg'],
        media: 'Oil on canvas, digital collage',
        dimensions: '2x3ft',
        description: 'An exquisite sculpture to adorn your living space.',
      },
      {
        id: 5,
        name: 'Fortis Fortuna Adiuvat',
        date: 2022,
        collection: 'Black Dog',
        price: 1000,
        image: ['/images/angel.JPG'],
        media: 'Graphite on paper, digital collage',
        dimensions: '30x40in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 6,
        name: 'Kirin',
        date: 2023,
        collection: '',
        price: 1000,
        image: ['/images/kirin.jpg'],
        media:'Graphic, charcoal and conte crayon on paper',
        dimensions: "18x24in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 7,
        name: 'Divinity in Hollowness',
        date: 2024,
        collection: '',
        price: 10000,
        image: ['/images/skeleton.jpg'],
        media:'Graphic, charcoal and conte crayon on paper',
        dimensions: "18x24in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 8,
        name: 'Solo/Sinnerman',
        date: 2021,
        collection: '',
        price: 1000,
        image: ['/images/solo-1.JPG'],
        media: "Graphite, marker, acrylic on paper",
        dimensions: '6x6in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 9,
        name: 'L\'homme noir et le chat',
        date: 2019,
        collection: 'Le Noir',
        price: 1000,
        image: ['/images/blackcat.jpg'],
        media: "Acrylic and oil on paper",
        dimensions: "9x12in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 10,
        name: 'The Amerikkkan Neighbor',
        date: 2021,
        collection: '',
        price: 12000,
        image: ['/images/Amerikkka.jpg'],
        media: 'Oil, acrylic, aluminum foil on canvas, digital collage',
        dimensions: '2x3ft',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 11,
        name: 'Smh, Bill, smh',
        date: 2019,
        collection: '',
        price: 50,
        image: ['/images/bill.jpg'],
        media: 'Collage on paper, digital',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 12,
        name: 'The Caped Woman',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/cloak.jpg'],
        media: 'Collage on paper, digital',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 13,
        name: 'FORESIGHT!',
        date: 2021,
        collection: '',
        price: 6000,
        image: ['/images/foresight.JPG'],
        media: 'Oil and digital collage',
        dimensions: '24x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 14,
        name: 'Godspeed Cowboy',
        date: 2020,
        collection: '',
        price: 15000,
        image: ['/images/godspeed.JPG'],
        media: 'Oil, acrylic, collage, charcoal, and fabric on canvas',
        dimensions: "18x24in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 15,
        name: 'The Painter & Consciousness',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/painter.JPG'],
        media: 'Collage on paper, digital',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 16,
        name: 'Transparent',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/wineglass.jpg'],
        media: 'Acrylic on paper',
        dimensions: '9x12in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 17,
        name: 'Sunday Morning Cowboy',
        date: 2020,
        collection: '',
        price: 1000,
        image: ['/images/sunday.jpg'],
        media: 'Oil, acrylic, fabric on canvas, and digital collage',
        dimensions: '18x24in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 18,
        name: 'I GOT MY REPARATIONS, BOUGHT MYSELF SOME JEWELRY!',
        date: 2020,
        collection: '',
        price: 7000,
        image: ['/images/reparations.JPG'],
        media: 'Acrylic, collage on canvas panel',
        dimensions: "9x9in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 19,
        name: 'Glitter will alwas make you feel better',
        date: 2019,
        collection: '',
        price: 7000,
        image: ['/images/glitter.jpg'],
        media: 'Acrylic, oil on canvas, digital',
        dimensions: "18x24in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 20,
        name: 'infinitum',
        date: 2019,
        collection: '',
        price: 2500,
        image: ['/images/infinitum.jpg'],
        media: 'Charcoal, marker, and acrylic on canvas',
        dimensions: "8x11in",
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 21,
        name: 'Anti',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/anti.jpg'],
        media: 'photography and digital print',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 22,
        name: 'Explicit Print',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/beachside.JPG'],
        media: 'digital print',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 23,
        name: 'Easy Way Out',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/exit.JPG'],
        media: 'photography and digital print',
        dimensions: '8.5x11in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 24,
        name: 'Seul-2',
        date: 2019,
        collection: 'Seul',
        price: 1000,
        image: ['/images/seul-2.JPG'],
        media: 'photography and digital print',
        dimensions: '18x24in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 25,
        name: 'Consciousness',
        date: 2019,
        collection: '',
        price: 2000,
        image: ['/images/swan.JPG'],
        media: 'Charcoal on paper, digital print',
        dimensions: '8x8in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 26,
        name: 'Sunday Radio',
        date: 2019,
        collection: '',
        price: 1000,
        image: ['/images/radio.jpg'],
        media: 'Charcoal on paper, digital print',
        dimensions: '8x8in',
        description: 'An exquisite sculpture to adorn your living space.',
      },
      {
        id: 27,
        name: 'Breathe Alone',
        date: 2019,
        collection: 'Seul',
        price: 1000,
        image: ['/images/seul-1.JPG'],
        media: 'photography and digital print',
        dimensions: '36x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 28,
        name: 'Contrasted Saturation',
        date: 2019,
        collection: '',
        price: 2000,
        image: ['/images/umbrella.jpg'],
        media: 'photography and digital print',
        dimensions: '36x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 29,
        name: 'Sacred Heartz',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/sacred.JPG'],
        media: 'photography and digital print',
        dimensions: '48x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 30,
        name: 'Subterranean Voyage',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/sub.JPG',],
        media: 'photography and digital print',
        dimensions: '36x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      },

      {
        id: 31,
        name: 'Chromed: SUDO RM -RF',
        date: 2023,
        collection: '',
        price: 5000,
        image: ['/images/chromed.JPG', '/images/chromedgreen.JPG', '/images/chromedred.JPG'],
        media: 'photography and digital print',
        dimensions: '36x18in',
        description: 'An exquisite sculpture to adorn your living space.',
      }
  ];
  
  export default products;